import React, { Component } from 'react';
import { instanceOf } from 'prop-types';
import { withCookies, Cookies } from 'react-cookie';
import { localStorageKey } from '../Const';
import {Diff2Html} from 'diff2html';
var jsdiff = require('diff');
require('colors');

const api_endpoint = "http://localhost:8080/api/exercise";


class Home extends Component {
  static propTypes = {
    cookies: instanceOf(Cookies).isRequired
  };

  /**
   * Constructor of this class
   * @param {*} props 
   */
  constructor(props) {
    super(props);
    this.state = {
      isLoading: false
      , isError: false
      , exercise: null

    };

    // binding
    this.getExerciseFromApiAsync = this.getExerciseFromApiAsync.bind(this);
  }

  /**
   * ComponentDidMount
   */
  componentDidMount() {
    const { cookies } = this.props;
    // console.log(cookies.get(localStorageKey));

    if (!this.state.exercise){
      this.getExerciseFromApiAsync();
    }
      
  }

  /**
   * fetch an exercise
   */
  async getExerciseFromApiAsync() {
    this.setState({
      isLoading: true,
    });

    const self = this;

    await fetch(api_endpoint)
      .then(function(response) {
        return response.json();
      })
      .then(function(content) {
        const exercise =  content.exercise;
        self.setState({
          isLoading: false,
          exercise: exercise,
        })
      })
      .catch(function(err) {
        console.error(err);
        self.setState({
          isLoading: false,
          isError: true,
        })
        return;
      })
  }

  /**
   * Render
   */
  render() {

    if (this.state.isError) {
      return (
        <div className="App">
          <p>An error occurred.</p>
        </div>
      )
    }

    if (this.state.isLoading | this.state.exercise === null) {
      return (
        <div className="App">
          <p>Loading...</p>
        </div>
      )
    }

    // extract information
    const exercise_raw = this.state.exercise;
    const exercise = {
      title: exercise_raw.title
      , bodyHTML: exercise_raw.bodyHTML
      , answerTitle: exercise_raw.pull_request.title
      , answerBodyHTML: exercise_raw.pull_request.bodyHTML
      , code_before: exercise_raw.code_change.before_body.split("\n")
      , code_after: exercise_raw.code_change.after_body.split("\n")
    }

    // Calculate code diff
    var code_diff_components = [];
    var diff = jsdiff.diffLines(exercise_raw.code_change.before_body, exercise_raw.code_change.after_body);
    diff.forEach(function(part){
      // green for additions, red for deletions
      // grey for common parts
      const color = part.added ? 'green' :
        part.removed ? 'red' : 'grey';
      code_diff_components.push(
        <span style={{color: color}}>
          {part.value}
        </span>
      )

      console.log(part.value, part.added, part.removed)
      
      // span = document.createElement('span');
      // span.style.color = color;
      // span.appendChild(document
      //   .createTextNode(part.value));
      // fragment.appendChild(span);
    });

    var diffHtml = Diff2Html.getPrettyHtml(
      "--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n",
      {inputFormat: 'diff', showFiles: false, matching: 'lines', outputFormat: 'side-by-side'}
    );

    return (
      <div className="container">

        <div className="row" dangerouslySetInnerHTML={{__html: diffHtml}}></div>

        {/* Exercise title and body */}
        <div className="row">
          <h2 className="font-weight-light mb-4">Q: { exercise.title }</h2>
        </div>
        <div className="row" dangerouslySetInnerHTML={{__html: exercise.bodyHTML}}></div>

        <hr></hr>

        {/* Answer */}
        <div className="row">
          <h2 className="font-weight-light mb-4">Answer: { exercise.answerTitle }</h2>
        </div>
        <div className="row" dangerouslySetInnerHTML={{__html: exercise.answerBodyHTML}}></div>
        {/* <div className="row">
          <div className="col-6">
            <code>{ exercise.code_before }</code>
          </div>
          <div className="col-6">
            <code>{ exercise.code_after }</code>
          </div>
        </div> */}
        {code_diff_components}

        {/* <div className="px-3 py-3 pt-md-5 pb-md-4 mx-auto w-50">
            <h3 className="font-weight-light mb-4">サインイン</h3>
            <form>
              <div className="form-group row">
                <label className="col-sm-3 col-form-label">名前</label>
                <input type="text" className="col-sm-7 form-control" placeholder="Enter name"/>
              </div>
              <div className="form-group row">
                <label className="col-sm-3 col-form-label">メールアドレス</label>
                <input type="email" className="col-sm-7 form-control" aria-describedby="emailHelp" placeholder="Enter email"/>
              </div>
              <div className="form-group">
                  <button type="submit" className="btn btn-primary">ユーザ登録</button>
              </div>
              <div className="form-group">
                <button type="submit" className="btn btn-outline-primary">サインイン</button>
              </div>
            </form>
          </div> */}
      </div>
    );
  }
}

export default withCookies(Home);
